CG研画集を追加
MISW/event-misw-jp pull request #20
Opened 2022-11-04 05:36 UTC by kkosugitm

# プルリクエストを行う前に、以下のことを確認してください。

- [ ] コードのフォーマットを行いましたか？
- [ ] エラーや警告を出さずに、正しくビルドされることを確認しましたか？
- [ ] 様々なブラウザ・OS・解像度でテストを行い、すべて正常に表示されましたか？
- [ ] サイズが 25 MiB を超えるファイルが存在しませんか？
- [ ] ライセンス感染するパッケージやライブラリ等を使用していませんか？ (例: GNU GPL・CC BY-SA )
- [ ] サインオフを行いましたか？ (例: Signed-off-by: mischan <miswchan@misw.jp> )
- [ ] プルリクエストを送信したら、Web の担当者と SysAd の担当者にコードレビューをリクエストしてください。
- [ ] 新しい特設サイトを追加する場合は、[misw-jp](https://github.com/MISW/misw-jp) のバナーも更新してください。

# プルリクエストの内容を以下に記載してください。
CG研画集を追加

# 特筆すべき内容があれば以下に記載してください。

2022-11-04 05:41 UTC, CaffeeLake requested changes

2022-11-04 05:41 UTC, CaffeeLake commented on src/wasedasai2022/index.html
> +                  <p>10:00-15:00</p>
```
                  <p>10:00-17:00</p>
```

2022-11-04 06:24 UTC, cherr0406 commented
別ページじゃなくて、トップページにダイレクトに載せるかんじ？
特にスマホだと縦長すぎてAccessまで辿り着くのに時間がかかるので、同人誌と同じように別ページにした方が見やすい気がします

2022-11-04 06:40 UTC, kkosugitm commented
分かりました。修正しておきます。
これから予定があるので、申し訳ないですが夜遅くになると思います。

2022-11-04 07:02 UTC, cherr0406 commented
了解です。教室展示もあるので、急がなくて大丈夫です👌

2022-11-05 04:56 UTC, cherr0406 approved these changes
遅れました、ページ分けありがとうございます。
出先で PC表示は確認できないのですが、スマホ表示は問題ありませんでしたので、PC表示に問題なければデプロイしてもらって大丈夫です。

2022-11-05 11:06 UTC, CaffeeLake approved these changes

2022-11-05 11:06 UTC, merged