Deploy: C101
MISW/event-misw-jp pull request #29
Opened 2022-12-25 08:03 UTC by idunafu

C101特設ページの設置

2022-12-25 09:28 UTC, CaffeeLake requested changes
- png は重いので WebP 等を使ってほしい。
- 作品のところ選択ができるのに、選択しても何も起こらない。

2022-12-25 09:30 UTC, CaffeeLake commented
- CI を通した。
- jQuery を cdnjs を使うように変更。
- リダイレクトを変更。

2022-12-25 11:17 UTC, CaffeeLake commented
- 画像を WebP に変換
- 未使用画像の削除
- Firefox でロードに 10 秒かかる問題を修正
- 作品紹介を選択できないように修正
- 高解像度モニターで左側に偏る問題を修正

2022-12-26 10:29 UTC, Meityo reviewed
お疲れ様です。サイトの制作ありがとうございます。
いくつか気になった点があったためコメント失礼します。

### 見た目について

- 以下の写真のように、ディスプレイによっては画面が表示された時にタイトルが見切れてしまいます。
こちら修正可能でしょうか？

![image](https://user-images.githubusercontent.com/121390671/209533582-43c92e8c-8e7d-4fc6-8846-1e13bfcbbcfe.png)

- 特にスマホから見たときに、画質というか背景の引き延ばされている感が強くて若干気になりました。高さをコンテンツに合わせている所為で横幅がかなり切られているのが原因なので、jsを使ってスクロールすると背景画像も一緒に降りていく形にすれば背景画像をもう少し大きく表示できる気はします…が面倒そうですし余裕がなければこのままで

### OGP画像について

- 画像内の文字が小さいため実際にTwitter上に表示されると見づらいかもしれません。
画像から日付・場所情報を省いて、「MIS.WCOMIC MARKET 101」（C101でも可）の文字を大きく配置していただけると助かります。
正方形のOGP画像のことも考慮すると情報が真ん中に集まっているとなおよいかと思います。
2022年度新歓サイトのものが参考になるかもしれません。
![image](https://user-images.githubusercontent.com/121390671/209532334-07598349-4fb4-4df5-b1e3-5f116c1469f7.png)


### その他

- 細かい所で恐縮ですが、CG研が今回頒布するのは同人誌ではなく画集なのでalt属性は「CG研究会画集の表紙」でお願いします。

https://github.com/MISW/event-misw-jp/blob/60fc3b3a7edc2d4b59edec85052c1f2ea1cd7c4a/src/c101/index.html#L89

それと権限がなくこちらではマージできない為、修正終わったら権限ある方のほうでマージしていただけると助かります。
よろしくお願いします。

2022-12-26 11:50 UTC, merged